name: Deploy Documentation

on:
  push:
    branches:
      - main  # Set this to your default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Copy files to docs
        run: cp README.md docs/

      - name: Build and Deploy to GitHub Pages
        run: |
          # This command builds the site and pushes it to the gh-pages branch
          mkdocs gh-deploy
          # --force
